# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f5c558cd5afa2119088673e06cf3677"
name = "app-staging"
handle = "app-staging-3"
application_url = "https://algebra-typing-subscriptions-tariff.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_metaobject_definitions,write_metaobject_definitions"

[auth]
redirect_urls = ["https://algebra-typing-subscriptions-tariff.trycloudflare.com/auth/callback", "https://algebra-typing-subscriptions-tariff.trycloudflare.com/auth/shopify/callback", "https://algebra-typing-subscriptions-tariff.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
